### ISSUE TITLE
Default export of `intl-messageformat-parser` is invalid

### ISSUE THREAD

**Issue by langri-sha** [formatjs/formatjs-old#115]
**Which package?**
`intl-messageformat-parser`

**Describe the bug**
Babel is not picking up exports from `intl-messageformat-parser`.

**To Reproduce**

```
import parser from 'intl-messageformat-parser`

parser.parse() // Calling `parse` on `undefined`
```

**Expected behavior**
Works as expected, without having to resort to:

```
const parser = require('intl-messageformat-parser')
```

**Additional context**
Perhaps missing some additional properties to flag this as an ES module?

**Comment by longlho** [comment]
import {parse} is the correct one. I’ll update the docs for it. Thanks for
reporting!

**Comment by Anticom** [comment]
I'm having the same issue.

I'm trying to extract the `react-intl` messages in a CRA using TypeScript.

```sh
$ create-react-app --info

Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.10.1 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 68.0
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-dom: ^16.8.6 => 16.8.6 
    react-scripts: 3.0.1 => 3.0.1 
  npmGlobalPackages:
    create-react-app: 3.0.1

```

**Edit:** I've used [`react-intl.macro`](https://github.com/evenchange4/react-intl.macro) to get the babel plugin into my CRA. Maybe this one messes with babel's settings so that it doesn't support ES6? There's a ticket open [over there](https://github.com/evenchange4/react-intl.macro/issues/84) for this issue.
