### ISSUE TITLE
Why we have to use new message content in each constructor?

### ISSUE THREAD

**Issue by mustafa519** [formatjs/formatjs-old#132]
I have a suggestion for `intl-messageformat` package.

**Numberformat** and **MessageFormat** functions are both so slow especially when we do construct them. I thought i wish there could be a different way to construct the **MessageFormat** function only with the language argument.

So i mean is that way possible to better as below?

```javascript

const currLangFormatter = new IntlMessageFormat('en-US');

const output = currLangFormatter
  .message(MESSAGES['en-US'].NUM_PHOTOS)
  .format({ numPhotos: 1000 });

console.log(output); // => "You have 1,000 photos."
```

I think, we won't need often for change the current language. Why we always have to construct new instance for same language to get the parsed content? Does it make sense? Or am i wrong because of less info about the package or logic?

I'm not so good at JS/ES but i think, that kind of logic could be better, what you guys think?

**Comment by longlho** [comment]
For historical context it was designed that way because parsing ICU messages was a lot slower than `new`-ing a class. Doing a `new IntlMessageFormat('en-US')` doesn't really do anything since we don't load CLDR data anymore.

To mitigate your problem you can certainly use `intl-format-cache` to memoize constructor.
