### ISSUE TITLE
Negative integers are not accepted as exact matches in plural argument.

### ISSUE THREAD

**Issue by bmurr** [formatjs/formatjs-old#146]
**Which package?**

intl-messageformat-parser

**Describe the bug**
Parsing this string: 

`{years, plural, =-1 {last year} =0 {this year} =1 {next year} other {{numYears} years {isPast, select, true {ago} other {ahead}}}}`

will fail with `Uncaught SyntaxError: Expected [0-9] but "-" found.` because of the `-1`.

I can't see any reason to disallow negative integers from being used as exact matches.

**Comment by longlho** [comment]
hmm this might be an issue in our parser yeah, let me check the ICU4J implementation. Although in terms of `plural` rules, negative numbers are treated the same way as positive number.

**Comment by guopengliang** [comment]
@longlho I think we should also fix negative number usage in "select".
I'm using an identical approach with negative number to address "last year", except that I use "select" instead of "plural".

`{diff, select, 0 {This Year} 1 {Next Year} -1 {Last Year} other {Annual}}`

Also note that there's no preceding "=" before the numbers. This used to work flawlessly with `react-intl@3.0.0-beta.18` and `@formatjs/intl-relativetimeformat@2.4.0`.

**Comment by longlho** [comment]
`select` doesn't have a concept of negative number, or number for that matter, the selector must be a valid identifier as defined [here](https://ssl.icu-project.org/apiref/icu4j/com/ibm/icu/text/SelectFormat.html) so basically dashes are not allowed.

**Comment by guopengliang** [comment]
I see. Thank you so much for the clarification.
