### ISSUE TITLE
Intl.ListFormat

### ISSUE THREAD

**Issue by klimashkin** [formatjs/formatjs-old#154]
Hi, since [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat) is already supported in Chrome and there is 100% [polyfill](https://github.com/wessberg/intl-list-format), maybe it's a good time to add its support to `intl-messageformat`, like:
`You have {count, plural, one {# new message} other {# new messages}} from these people: {people, list}`

And also add type for ListFormat into intl-format-cache.

**Comment by longlho** [comment]
yeah that's definitely in our roadmap, further discussion: https://github.com/formatjs/react-intl/issues/1328

If you have some thoughts on API & message format semantics feel free to share them as well.

Right now I'm actually working on polyfilling https://github.com/tc39/proposal-unified-intl-numberformat since it's quite useful (allow you to format things like `1Kb` or `12m/s`)

**Comment by klimashkin** [comment]
Awesome!

We don't use react-intl, dropped its usage in the end of 2014 : ), but just pure intl-messageformat instead.
And api inside the message might be 
just `{param, list}`
with optional `{param, list, {style: 'long', type: 'conjunction'}}`

**Comment by longlho** [comment]
ICU messageformat has been traditionally ambiguous in its level of support for custom format. Introducing `list` would mean supporting custom formatters which require some more thinking around. We'll try to tackle that next.
