### ISSUE TITLE
Collect messages even if defaultMessage prop is missing

### ISSUE THREAD

**Issue by danousna** [formatjs/formatjs-old#294]
**Which package?**
`babel-plugin-react-intl`

**Is your feature request related to a problem? Please describe.**
I do not use the `defaultMessage` prop in my react-intl project, only the ID. This package does not collect my messages if the `defaultMessage` prop is missing when using the `FormattedMessage` component. I have seen in the package code that it appears to be a voluntary decision.

**Describe the solution you'd like**
Provide an option to collect messages even if the `defaultMessage` prop is missing.

**Comment by longlho** [comment]
Are you looking for a `json` file with only IDs?

**Comment by danousna** [comment]
Yes, that's it. I have re-implemented my own solution inspired by this package but I am just wondering why it forces the use of defaultMessage ?

**Comment by longlho** [comment]
Because that's the typical dev flow of declaring the messages inline (so contexts are captured) and we also have linter for missing placeholders and various other stuff as well. Having just an ID is not really the workflow we're supporting cause you can easily write a babel plugin just to extract that.

If anything the `ID` can be made optional cause that can be generated as a hash from `defaultMessage` + `description`.

**Comment by danousna** [comment]
Oh ok I see, thanks for the answer, I might do that actually.
Closing this then.
