### ISSUE TITLE
node_modules/@formatjs/intl-utils/dist/invariant.d.ts:1:92 - error TS1144: '{' or ';' expected.

### ISSUE THREAD

**Issue by shanhuiyang** [formatjs/formatjs-old#410]
**Which package?**
IntlMessageFormat

**Describe the bug**
Build error from Typescript

**To Reproduce**
`"intl-messageformat": "^7.7.5"`

run tsc

```
$ tsc
node_modules/@formatjs/intl-utils/dist/invariant.d.ts:1:92 - error TS1144: '{' or ';' expected.
1 export declare function invariant(condition: boolean, message: string, Err?: any): asserts condition;
                                                                                             ~~~~~~~~~
Found 1 error.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by longlho** [comment]
Seems like you need to install TS3.7+ or pin to the previous version

**Comment by CarstenLeue** [comment]
In my case the problem comes in as a transitive dependency via `intl-messageformat#intl-messageformat-parser#@formatjs#intl-unified-numberformat`
For that reason it is no option to pin the version to the previous one. The version number of `intl-messageformat` has not changed.

It is also not an option to upgrade to TS 3.7 because other libraries I am using (e.g. ng-packagr) do not support TS 3.7.

A requirement for a higher TS version means an **incompatible change** in the public API of this component and this requires a change in the major version number of the component (if you follow the semantic versioning approach).

I suggest to undo the change for the v2 stream and introduce a v3 stream with the new TS dependency.

**Comment by Xceno** [comment]
We've got the same problem as @CarstenLeue. A dependency of ours needs formatjs, but unfortunately didn't pin the version. We're also unable to upgrade to TS 3.7 because of other incompatibilities. So our build remains broken.
