### ISSUE TITLE
Messages with duplicate ids are ignored

### ISSUE THREAD

**Issue by maciej-gurban** [formatjs/formatjs-old#67]
For the following input:
```
defineMessages({
  foo: {
    id: 'foo',
    defaultMessage: 'Foo',
  },
  bar: {
    id: 'foo',
    defaultMessage: 'Foo',
  },
});
```

The parsing will silently ignore one of the messages. In the above example if the values of `defaultMessage` are different, the parsing will throw.

I'd expect the behavior to be that whenever two messages with identical keys are found within one `defineMessages()`, an error should be thrown since from my perspective that's a developer mistake and we should never have two messages with identical ids and values.

**Comment by tmkasun** [comment]
I too have the same concern, If someone has used `FormattedMessage` in one file like below

```xml
    <FormattedMessage id='cancel' defaultMessage='Cancel' />
```

and if another developer adds `FormattedMessage` with the same ID but different default message

```xml
    <FormattedMessage id='cancel' defaultMessage='Cancel Loading' />
```

IMO , It's a developer mistake and should throw an exception or warning ?

Because in locale file (i:e en.json), we couldn't have the same ID mapping two values.

**Comment by lexax666** [comment]
@tmkasun did you ever resolve this issue?

**Comment by tmkasun** [comment]
@lexax666 , I'm still having the issue 😞
